main: com.winthier.minigames.spleef.Spleef
name: Spleef

version: 0.1
api-version: 1.17

description: The popular Spleef mini game
authors: [ StarTux ]
website: https://cavetale.com

depend: []
softdepend: []

commands: {}

permissions: {}
