main: com.winthier.spleef.SpleefPlugin
name: Spleef

version: 0.1
api-version: 1.17

description: The popular Spleef mini game
authors: [StarTux]
website: https://cavetale.com

depend: [Core, Mytems, Spawn, Sidebar]
softdepend: []

commands:

  spleef:
    aliases: [spleefadmin]
    description: Admin command
    permission: spleef.admin

permissions:

  spleef.admin:
    description: Admin permission
    default: op
