main: com.winthier.spleef.SpleefPlugin
name: Spleef

version: 0.1
api-version: '1.21.10'

description: The popular Spleef mini game
authors: [StarTux]
website: https://cavetale.com

depend: [Core, PlayerCache, Mytems, Spawn, Fam, Creative]
softdepend: []

commands:

  spleef:
    aliases: []
    description: User command
    permission: spleef.spleef

  spleefadmin:
    aliases: [spleefadm]
    description: Admin command
    permission: spleef.admin

permissions:

  spleef.spleef:
    description: Use /spleef
    default: true

  spleef.admin:
    description: Admin permission
    default: op
